# Generated by Django 5.0.4 on 2024-05-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Страна')),
                ('identity_nalog_number', models.IntegerField(verbose_name='ИНН')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
